//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_KutuphaneSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hareketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hareketler()
        {
            this.Cezalar = new HashSet<Cezalar>();
        }
    
        public int ID { get; set; }
        public Nullable<int> KitapID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<int> PersonelID { get; set; }
        public Nullable<System.DateTime> AlisTarihi { get; set; }
        public Nullable<System.DateTime> IadeTarihi { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> UyeninGetirdigiTarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cezalar> Cezalar { get; set; }
        public virtual Kitaplar Kitaplar { get; set; }
        public virtual Personeller Personeller { get; set; }
        public virtual Uyeler Uyeler { get; set; }
    }
}
